//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlairGraphic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class application_template
    {
        public int application_template_id { get; set; }
        public int application_template_type_id { get; set; }
        public string application_template_name { get; set; }
        public string application_template_subject { get; set; }
        public string application_template_body { get; set; }
        public string application_template_attachment_1 { get; set; }
        public string application_template_attachment_2 { get; set; }
        public string application_template_attachment_3 { get; set; }
        public string application_template_attachment_4 { get; set; }
        public string application_template_attachment_5 { get; set; }
        public bool is_html { get; set; }
        public bool is_public { get; set; }
        public int company_id { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<int> updated_by { get; set; }
        public bool is_active { get; set; }
    
        public virtual application_template_type application_template_type { get; set; }
        public virtual company company { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
