//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlairGraphic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_holiday
    {
        public int company_holiday_id { get; set; }
        public string holiday_name { get; set; }
        public System.DateTime holiday_date { get; set; }
        public int company_id { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<int> updated_by { get; set; }
        public bool is_active { get; set; }
    
        public virtual company company { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
