//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlairGraphic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public job()
        {
            this.job_assignment = new HashSet<job_assignment>();
            this.job_attachment = new HashSet<job_attachment>();
        }
    
        public int job_id { get; set; }
        public int job_type_id { get; set; }
        public int client_id { get; set; }
        public int paper_type_id { get; set; }
        public Nullable<int> paper_sub_type_id { get; set; }
        public Nullable<int> lemination_type_id { get; set; }
        public int job_status_id { get; set; }
        public int quantity { get; set; }
        public string comment { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<int> updated_by { get; set; }
        public int company_id { get; set; }
        public bool is_active { get; set; }
    
        public virtual company company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job_assignment> job_assignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job_attachment> job_attachment { get; set; }
        public virtual job_status job_status { get; set; }
        public virtual job_type job_type { get; set; }
        public virtual lemination_type lemination_type { get; set; }
        public virtual paper_sub_type paper_sub_type { get; set; }
        public virtual paper_type paper_type { get; set; }
        public virtual user user { get; set; }
    }
}
