//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlairGraphic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class package_subscription
    {
        public int package_subscription_id { get; set; }
        public System.DateTime subscription_start_date { get; set; }
        public System.DateTime subscription_end_date { get; set; }
        public int allow_users { get; set; }
        public decimal subscription_price { get; set; }
        public decimal subscription_discount { get; set; }
        public string subscription_tax_display { get; set; }
        public decimal subscription_tax_percentage { get; set; }
        public decimal subscription_tax { get; set; }
        public int user_id { get; set; }
        public int package_id { get; set; }
        public int duration_days_id { get; set; }
        public decimal setup_cost { get; set; }
        public decimal per_user_price { get; set; }
        public bool is_public { get; set; }
        public int payment_status_id { get; set; }
        public int company_id { get; set; }
        public System.DateTime created_date { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<int> updated_by { get; set; }
        public bool is_active { get; set; }
        public string online_payment_fields { get; set; }
        public string payment_detail { get; set; }
        public string cancel_remark { get; set; }
    
        public virtual company company { get; set; }
        public virtual duration_days duration_days { get; set; }
        public virtual package package { get; set; }
        public virtual user user { get; set; }
        public virtual payment_status payment_status { get; set; }
        public virtual user user1 { get; set; }
        public virtual user user2 { get; set; }
        public virtual user user3 { get; set; }
    }
}
