//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlairGraphic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class role_menu
    {
        public int role_menu_id { get; set; }
        public int role_id { get; set; }
        public int menu_id { get; set; }
        public int company_id { get; set; }
        public bool is_active { get; set; }
    
        public virtual company company { get; set; }
        public virtual menu menu { get; set; }
        public virtual role role { get; set; }
    }
}
