//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlairGraphic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sub_area
    {
        public int sub_area_id { get; set; }
        public string sub_area_name { get; set; }
        public int display_order { get; set; }
        public int area_id { get; set; }
        public bool is_active { get; set; }
    
        public virtual area area { get; set; }
    }
}
