//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlairGraphic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class time_format
    {
        public int time_format_id { get; set; }
        public string time_format_name { get; set; }
        public string time_format_code_csharp { get; set; }
        public string time_format_code_js { get; set; }
        public bool is_active { get; set; }
    }
}
